_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 500

precision: 32

resume_from_checkpoint: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0

terminate_on_nan: True

# extra tricks
gradient_clip_val: 0.5
stochastic_weight_avg: True
