# dvc project pipeline

stages:
  createtiles:
    cmd: >-
      mkdir data/processed;
      gdal_retile.py 
      -csv locations.csv 
      -v -ps ${createtiles.size} ${createtiles.size}
      -co "TILED=YES" -co "COMPRESS=LZW" 
      -targetDir data/processed 
      data/raw/tif_ortho_2019.tif
    deps:
    - data/raw/tif_ortho_2019.tif
    params:
    - createtiles.size
    outs:
    - data/processed

  createmasks:
    cmd: >-
      python createmasks.py data/processed data/processed.masks data/raw/dead_treed_proj.shp
    deps:
    - data/processed
    - data/raw/dead_treed_proj.shp
    - data/raw/dead_treed_proj.shx
    - data/raw/dead_treed_proj.dbf
    - data/raw/dead_treed_proj.prj
    outs:
    - data/processed.masks 

  # createsubtiles:

  # train:
