# dvc project pipeline

stages:
  createtiles:
    cmd: >-
      mkdir data/processed;
      gdal_retile.py 
      -csv locations.csv 
      -v -ps ${source_dim} ${source_dim}
      -co "TILED=YES" -co "COMPRESS=LZW" 
      -targetDir data/processed 
      data/raw/tif_ortho_2019.tif
    deps:
    - data/raw/tif_ortho_2019.tif
    params:
    - source_dim
    outs:
    - data/processed

  createmasks:
    cmd: >-
      python createmasks.py data/processed data/processed.masks data/raw/dead_treed_proj.shp
    deps:
    - data/processed
    - data/raw/dead_treed_proj.shp
    - data/raw/dead_treed_proj.shx
    - data/raw/dead_treed_proj.dbf
    - data/raw/dead_treed_proj.prj
    outs:
    - data/processed.masks 

  createdataset:
    cmd: >-
      python createdataset.py data/processed data/processed.masks data/dataset 
      --source_dim ${source_dim}
      --tile_size ${createdataset.tile_size}
      --format ${file_type}
    deps:
    - data/processed
    - data/processed.masks 
    params:
    - source_dim
    - createdataset.tile_size
    - file_type
    outs:
    - data/dataset/train
    - data/dataset/stats.csv 

  createbalanced:
    cmd: >-
      python createbalanced.py 
      data/dataset/stats.csv
      data/dataset/train 
      data/dataset/train_balanced 
      data/dataset/train_balanced_short
      --format ${file_type}
    deps:
    - data/dataset/train
    params:
    - file_type
    outs:
    - data/dataset/train_balanced
    - data/dataset/train_balanced_short

  # train:
