name: deadtrees
channels:
  - fastchan
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab=3
  - pytorch>=1.9
  - torchvision>=0.10
  - pytorch-lightning
  - opencv-python-headless
  - numpy
  - pandas
  - albumentations
  - dvc-s3 
  - rich 
  - python-dotenv 
  - pydantic 
  - wandb 
  - pip:
    - webdataset
    - monai==0.5.3
    - hydra-core --pre
    - hydra-colorlog --pre
    #- --no-deps -e .
    