name: deadtrees
channels:
  - pytorch
  - nvidia
  - conda-forge
  dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.1
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch>=1.9
  - torchvision>=0.10
  - opencv
  - nb_conda_kernels
  - numpy
  - pandas
  - albumentations
  - dvc-s3 
  - rich 
  - python-dotenv 
  - pydantic 
  - wandb 
  - pip:
    - webdataset
    - hydra-core
    - hydra-colorlog
    - pytorch-lightning 
    - segmentatopn-models-pytorch
    #- --no-deps -e .
    