# @package _group_
_target_: deadtrees.network.segmodel.SemSegment

network_conf:
  architecture: unetplusplus #unet
  encoder_name: efficientnet-b6 #resnet34
  decoder_channels: [256, 128, 64, 32, 16]
  encoder_depth: 5
  encoder_weights: "imagenet"
