_target_: src.network.segmodel.SemSegment

network:
    architecture: efficientunet++ #unet
    encoder_name: efficientnet-b5 #resnet34
    decoder_channels: [256, 128, 64, 32, 16]
    encoder_depth: 5
    encoder_weights: "imagenet"
    losses: ["GDICE", "FOCAL", "BOUNDARY-RAMPED"]   # GDICE, FOCAL, BOUNDARY, BOUNDARY-RAMPED

training:
    learning_rate: 0.0003 #3 #0.00015 #0.0001
    cosineannealing_tmax: 20  # number of epochs for one cosine annealing cycle (default: 10)
