_target_: deadtrees.network.segmodel.SemSegment

network:
    architecture: efficientunet++ #unet
    encoder_name: efficientnet-b5 #resnet34
    decoder_channels: [256, 128, 64, 32, 16]
    encoder_depth: 5
    encoder_weights: "imagenet"  #null
    losses: ["GDICE", "FOCAL", "BOUNDARY"]   # GWDICE, GDICE, DICE, FOCAL, BOUNDARY or BOUNDARY-RAMPED

training:
    learning_rate: 0.0003
    cosineannealing_tmax: 10  # number of epochs for one cosine annealing cycle (default: 10)
