# @package _global_
datamodule:
  _target_: deadtrees.data.deadtreedata.DeadtreesDataModule
  pattern: "train-combo-*.tar"
  train_dataloader_conf:
    batch_size: 32
    num_workers: 4
  val_dataloader_conf:
    batch_size: 32
    num_workers: 4
  test_dataloader_conf:
    batch_size: 32
    num_workers: 4

model:
  network:
    classes: ["background", "deadtree"]
    in_channels: 4
