# @package _global_
datamodule:
  _target_: src.data.deadtreedata.DeadtreesDataModule
  pattern: "train-balanced-000*.tar"
  pattern_extra: ["train-negativesamples-000*.tar", "train-randomsamples-000*.tar"]
  batch_size_extra: [2, 15]
  train_dataloader_conf:
    batch_size: 32
    num_workers: 2
  val_dataloader_conf:
    batch_size: 32
    num_workers: 2
  test_dataloader_conf:
    batch_size: 32
    num_workers: 2

model:
  network_conf:
    classes: 3
    in_channels: 4
